name: meng-ui-deploy

on:
  # 手动运行工作流程（workflow_dispatch 事件触发器配置后可以在actions下手动运行工作流）
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  # jobs的id
  build-add-deploy:
    # 指定服务器的运行环境：最新版本ubuntu
    runs-on: ubuntu-latest
    steps:
      # 使用actions/checkout@v4 库拉取代码到ubuntu上
      - name: checkout
        uses: actions/checkout@v4

      # 安装pnpm
      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 打包成静态文件
      - name: build
        run: pnpm install && pnpm build
